apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lo38akr6p-python
  janus-idp.io/tekton: lo38akr6p-python
  backstage.io/kubernetes-id: lo38akr6p-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lo38akr6p-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
